      - name: Check AAB
        run: |
          echo "Checking for AAB..."
          ls -lh android/app/build/outputs/bundle/release/

      - name: Upload signed AAB
        uses: actions/upload-artifact@v4
        with:
          name: dxball-classic-signed-aab
          path: android/app/build/outputs/bundle/release/*.aab
          if-no-files-found: error
